services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/tmp
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://cinema:cinema@db:5432/cinema?sslmode=disable
      REDIS_ADDR: redis:6379
    command: air

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
